### ISSUE TITLE
Add new models

### ISSUE THREAD

**Issue by MKaptein** [scailable/sclblpy#20]
The list of models we export is actually larger than in mentioned in the current version. We need to update the docs and "re-push" the package.

**Comment by robinvanemden** [comment]
|  | Classification | Regression |
| --- | --- | --- |
| **Linear** | <ul><li>scikit-learn<ul><li>LogisticRegression</li><li>LogisticRegressionCV</li><li>PassiveAggressiveClassifier</li><li>Perceptron</li><li>RidgeClassifier</li><li>RidgeClassifierCV</li><li>SGDClassifier</li></ul></li><li>lightning<ul><li>AdaGradClassifier</li><li>CDClassifier</li><li>FistaClassifier</li><li>SAGAClassifier</li><li>SAGClassifier</li><li>SDCAClassifier</li><li>SGDClassifier</li></ul></li></ul> | <ul><li>scikit-learn<ul><li>ARDRegression</li><li>BayesianRidge</li><li>ElasticNet</li><li>ElasticNetCV</li><li>HuberRegressor</li><li>Lars</li><li>LarsCV</li><li>Lasso</li><li>LassoCV</li><li>LassoLars</li><li>LassoLarsCV</li><li>LassoLarsIC</li><li>LinearRegression</li><li>OrthogonalMatchingPursuit</li><li>OrthogonalMatchingPursuitCV</li><li>PassiveAggressiveRegressor</li><li>RANSACRegressor(only supported regression estimators can be used as a base estimator)</li><li>Ridge</li><li>RidgeCV</li><li>SGDRegressor</li><li>TheilSenRegressor</li></ul><li>StatsModels<ul><li>Generalized Least Squares (GLS)</li><li>Generalized Least Squares with AR Errors (GLSAR)</li><li>Ordinary Least Squares (OLS)</li><li>[Gaussian] Process Regression Using Maximum Likelihood-based Estimation (ProcessMLE)</li><li>Quantile Regression (QuantReg)</li><li>Weighted Least Squares (WLS)</li></ul><li>lightning<ul><li>AdaGradRegressor</li><li>CDRegressor</li><li>FistaRegressor</li><li>SAGARegressor</li><li>SAGRegressor</li><li>SDCARegressor</li></ul></li></ul> |
| **SVM** | <ul><li>scikit-learn<ul><li>LinearSVC</li><li>NuSVC</li><li>SVC</li></ul></li><li>lightning<ul><li>KernelSVC</li><li>LinearSVC</li></ul></li></ul> | <ul><li>scikit-learn<ul><li>LinearSVR</li><li>NuSVR</li><li>SVR</li></ul></li><li>lightning<ul><li>LinearSVR</li></ul></li></ul> |
| **Tree** | <ul><li>DecisionTreeClassifier</li><li>ExtraTreeClassifier</li></ul> | <ul><li>DecisionTreeRegressor</li><li>ExtraTreeRegressor</li></ul> |
| **Random Forest** | <ul><li>ExtraTreesClassifier</li><li>LGBMClassifier(rf booster only)</li><li>RandomForestClassifier</li><li>XGBRFClassifier(binary only, multiclass is not supported yet)</li></ul> | <ul><li>ExtraTreesRegressor</li><li>LGBMRegressor(rf booster only)</li><li>RandomForestRegressor</li><li>XGBRFRegressor</li></ul> |
| **Boosting** | <ul><li>LGBMClassifier(gbdt/dart/goss booster only)</li><li>XGBClassifier(gbtree/gblinear booster only)</li><ul> | <ul><li>LGBMRegressor(gbdt/dart/goss booster only)</li><li>XGBRegressor(gbtree/gblinear booster only)</li></ul> |

**Comment by MKaptein** [comment]
In the midst of adding this, but needs an update of the toolchain to support `lightgbm` (which is also the package name in the bundle).

**Comment by MKaptein** [comment]
Ran tests for:


package | model | New | Tested (01052020) | Note
-- | -- | -- | -- | --
lightgbm | LGBMClassifier(rf booster only) | yes | ok |  
lightgbm | LGBMRegressor(rf booster only) | yes | ok |  
lightning | AdaGradClassifier | yes | no | Skip for now
lightning | AdaGradRegressor | yes | no | Skip for now
lightning | CDClassifier | yes | no | Skip for now
lightning | CDRegressor | yes | no | Skip for now
lightning | FistaClassifier | yes | no | Skip for now
lightning | FistaRegressor | yes | no | Skip for now
lightning | KernelSVC | yes | no | Skip for now
lightning | SAGAClassifier | yes | no | Skip for now
lightning | SAGARegressor | yes | no | Skip for now
lightning | SAGClassifier | yes | no | Skip for now
lightning | SAGRegressor | yes | no | Skip for now
lightning | SDCAClassifier | yes | no | Skip for now
lightning | SDCARegressor | yes | no | Skip for now
sklearn | ARDRegression | no | ok |  
sklearn | BayesianRidge | yes | ok |  
sklearn | DecisionTreeClassifier | no | ok |  
sklearn | DecisionTreeRegressor | no | ok |  
sklearn | ElasticNet | no | ok |  
sklearn | ElasticNetCV | no | ok |  
sklearn | ExtraTreeClassifier | no | ok |  
sklearn | ExtraTreeRegresso | no | ok |  
sklearn | ExtraTreesClassifier | no | ok |  
sklearn | ExtraTreesRegressor | no | ok |  
sklearn | HuberRegressor | no | ok |  
sklearn | Lars | no | ok |  
sklearn | LarsCV | no | ok |  
sklearn | Lasso | no | ok |  
sklearn | LassoCV | no | ok |  
sklearn | LassoLars | no | ok |  
sklearn | LassoLarsCV | no | ok |  
sklearn | LassoLarsIC | no | ok |  
sklearn | LinearRegression | no | ok |  
sklearn | LinearSVC | no | ok |  
sklearn | LinearSVR | no | ok |  
sklearn | LogisticRegression | yes | ok |  
sklearn | LogisticRegressionCV | yes | ok |  
sklearn | NuSVC | no | ok |  
sklearn | NuSVR | no | ok |  
sklearn | OrthogonalMatchingPursuit | no | ok |  
sklearn | OrthogonalMatchingPursuitCV | no | ok |  
sklearn | PassiveAggressiveClassifier | no | ok |  
sklearn | PassiveAggressiveRegressor | no | ok |  
sklearn | Perceptron | yes | ok |  
sklearn | RandomForestClassifier | no | ok |  
sklearn | RandomForestRegressor | no | ok |  
sklearn | RANSACRegressor | no | ok |  
sklearn | Ridge | no | ok |  
sklearn | RidgeClassifier | yes | ok |  
sklearn | RidgeClassifierCV | yes | ok |  
sklearn | RidgeCV | no | ok |  
sklearn | SGDClassifier | no | ok |  
sklearn | SGDRegressor | no | ok |  
sklearn | SVC | no | ok |  
sklearn | SVR | no | ok |  
sklearn | TheilSenRegressor | no | ok |  
statsmodels | [Gaussian] Process Regression Using Maximum Likelihood-based Estimation (ProcessMLE) | yes | not ok | Skip for now
statsmodels | Generalized Least Squares (GLS) |   | ok |  
statsmodels | Generalized Least Squares with AR Errors (GLSAR) | yes | ok |  
statsmodels | Ordinary Least Squares (OLS) |   | ok |  
statsmodels | Quantile Regression (QuantReg) | yes | ok |  
statsmodels | Weighted Least Squares (WLS) |   | ok |  
xgboost | XGBClassifier(gbtree/gblinear booster only) | no | ok |  
xgboost | XGBRegressor(gbtree/gblinear booster only) | no | ok |  
xgboost | XGBRFClassifier(binary only, multiclass is not supported yet) | no | ok |  
xgboost | XGBRFRegressor | no | ok |  

So, added a few models (including lightgbm) and xgboost. Not added the lightning ones (although in `test_all_models.py` these are specified already and they should be simple to add by:

1. Checking if _model_fitted() and _precit() work for lightning models
2. Mapping the lightning package to the sklearn toolchain (in main.py)
3. Running the tests.

I am closing this for now.

**Comment by MKaptein** [comment]
package | model | Tested (05052020) | Note
-- | -- | -- | --
lightgbm | LGBMClassifier | ok |  
lightgbm | LGBMRegressor | ok |  
sklearn | ARDRegression | ok |  
sklearn | BayesianRidge | ok |  
sklearn | DecisionTreeClassifier | ok |  
sklearn | DecisionTreeRegressor | ok |  
sklearn | ElasticNet | ok |  
sklearn | ElasticNetCV | ok |  
sklearn | ExtraTreeClassifier | ok |  
sklearn | ExtraTreeRegresso | ok |  
sklearn | ExtraTreesClassifier | ok |  
sklearn | ExtraTreesRegressor | ok |  
sklearn | HuberRegressor | ok |  
sklearn | Lars | ok |  
sklearn | LarsCV | ok |  
sklearn | Lasso | ok |  
sklearn | LassoCV | ok |  
sklearn | LassoLars | ok |  
sklearn | LassoLarsCV | ok |  
sklearn | LassoLarsIC | ok |  
sklearn | LinearRegression | ok |  
sklearn | LinearSVC | ok |  
sklearn | LinearSVR | ok |  
sklearn | LogisticRegression | ok |  
sklearn | LogisticRegressionCV | ok |  
sklearn | NuSVC | ok |  
sklearn | NuSVR | ok |  
sklearn | OrthogonalMatchingPursuit | ok |  
sklearn | OrthogonalMatchingPursuitCV | ok |  
sklearn | PassiveAggressiveClassifier | ok |  
sklearn | PassiveAggressiveRegressor | ok |  
sklearn | Perceptron | ok |  
sklearn | RandomForestClassifier | ok |  
sklearn | RandomForestRegressor | ok |  
sklearn | RANSACRegressor | ok |  
sklearn | Ridge | ok |  
sklearn | RidgeClassifier | ok |  
sklearn | RidgeClassifierCV | ok |  
sklearn | RidgeCV | ok |  
sklearn | SGDClassifier | ok |  
sklearn | SGDRegressor | ok |  
sklearn | SVC | ok |  
sklearn | SVR | ok |  
sklearn | TheilSenRegressor | ok |  
statsmodels | Generalized Least Squares (GLS) | ok |  
statsmodels | Generalized Least Squares with AR Errors (GLSAR) | ok |  
statsmodels | Ordinary Least Squares (OLS) | ok |  
statsmodels | Quantile Regression (QuantReg) | ok |  
statsmodels | Weighted Least Squares (WLS) | ok |  
xgboost | XGBClassifier | ok |  
xgboost | XGBRegressor | ok |  
xgboost | XGBRFClassifier | ok | Binary only
xgboost | XGBRFRegressor | ok |
