### ISSUE TITLE
Docs URL in readme.md points to broken url

### ISSUE THREAD

**Issue by VincentGijsen** [scailable/sclblpy#31]
the *https://docs.sclbl.net/sclblpy* on the README.md doesn't work

**Comment by MKaptein** [comment]
Thanks for pointing that one out: we will fix it. For now, check the docs at [https://pypi.org/project/sclblpy/](https://pypi.org/project/sclblpy/).

**Comment by robinvanemden** [comment]
https://docs.sclbl.net/sclblpy now redirects to https://pypi.org/project/sclblpy/ :)

**Comment by MKaptein** [comment]
Note: The project now also contains a `/docs/` folder with main.m.hmtl generated by `pdoc`; we might use this at some point although I think the current solution is fine.
