### ISSUE TITLE
Possibly missing an import in Getting Started 101

### ISSUE THREAD

**Issue by msm1089** [scailable/sclblpy#42]
At https://github.com/scailable/sclbl-tutorials/blob/master/sclbl-101-getting-started/README.md the line `sp.upload(lm, fv, docs=docs)` uses a variable `sp`. I could not see any reference to this, but assume somewhere there should be `import sclblpy as sp`.

**Comment by MKaptein** [comment]
Hi, 

Thanks for the message; I just added the import statement.
